### ISSUE TITLE
Program received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#25]
rpm -q provami-qt
provami-qt-1.1-1.fc20.x86_64

rpm -q dballe
dballe-7.11-1.x86_64

dbadb info --dsn=sqlite:/tmp/qcspa.sqlite 
Default format for new DBs: V6
Format: V6

[qcspa.zip](https://github.com/ARPA-SIMC/provami/files/227621/qcspa.zip)

```
gdb provami-qt  sqlite:///tmp/qcspa.sqlite
GNU gdb (GDB) Fedora 7.7.1-21.fc20
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from provami-qt...Reading symbols from /scratch/ppatruno/provami-qt...(no debugging symbols found)...done.
(no debugging symbols found)...done.
/scratch/ppatruno/sqlite:///tmp/qcspa.sqlite: File o directory non esistente.
Missing separate debuginfos, use: debuginfo-install provami-qt-1.1-1.fc20.x86_64
(gdb) run  sqlite:///tmp/qcspa.sqlite
Starting program: /usr/bin/provami-qt sqlite:///tmp/qcspa.sqlite

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib64/libgobject-2.0.so.0.3800.2-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 3, in <module>
    import gdb.backtrace
ImportError: No module named backtrace
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib64/libgobject-2.0.so.0.3800.2-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 3, in <module>
    import gdb.backtrace
ImportError: No module named backtrace
[New Thread 0x7ffff08d7700 (LWP 10130)]
[New Thread 0x7fffea7a9700 (LWP 10132)]
[New Thread 0x7fffa3cd3700 (LWP 10133)]
[New Thread 0x7fffa34cb700 (LWP 10134)]
[New Thread 0x7fffa2cab700 (LWP 10135)]
[New Thread 0x7fffa1eba700 (LWP 10136)]
setNativeLocks failed: Risorsa temporaneamente non disponibile
setNativeLocks failed: Risorsa temporaneamente non disponibile
progress  "data" : new task:  "Loading data..."
[New Thread 0x7fffa11b8700 (LWP 10137)]
progress  "summary" : new task:  "Loading summary..."
progress  "summary" : task update:  "Loading summary from db..."
[New Thread 0x7fffa09b7700 (LWP 10138)]
[New Thread 0x7fff8b960700 (LWP 10139)]
[New Thread 0x7fff8b15f700 (LWP 10140)]
progress  "data" : task update:  "Processing data..."
progress  "data" : task ends
progress  "summary" : task update:  "Processing summary..."
Refresh summary results arrived

Program received signal SIGSEGV, Segmentation fault.
dballe::db::v6::cursor::(anonymous namespace)::Data::get_var (this=0x9ed558) at db/v6/cursor.cc:310
310     wreport::Var get_var() const override { return Var(varinfo(results[cur].out_varcode), results[cur].out_value); }
(gdb) 
(gdb) where
#0  dballe::db::v6::cursor::(anonymous namespace)::Data::get_var (this=0x9ed558) at db/v6/cursor.cc:310
#1  0x0000003c11729df8 in dballe::db::summary::Entry::Entry (this=0x9e7e20, cur=..., want_details=<optimized out>)
    at db/summary.cc:18
#2  0x0000003c1172b44d in construct<dballe::db::summary::Entry, dballe::db::CursorSummary&, bool&> (__p=<optimized out>, 
    this=0xa85970) at /usr/include/c++/4.8.3/ext/new_allocator.h:120
#3  _S_construct<dballe::db::summary::Entry, dballe::db::CursorSummary&, bool&> (__p=<optimized out>, __a=...)
    at /usr/include/c++/4.8.3/bits/alloc_traits.h:254
#4  construct<dballe::db::summary::Entry, dballe::db::CursorSummary&, bool&> (__p=<optimized out>, __a=...)
    at /usr/include/c++/4.8.3/bits/alloc_traits.h:393
#5  std::vector<dballe::db::summary::Entry, std::allocator<dballe::db::summary::Entry> >::_M_emplace_back_aux<dballe::db::CursorSummary&, bool&> (this=this@entry=0xa85970) at /usr/include/c++/4.8.3/bits/vector.tcc:408
#6  0x0000003c1172a691 in emplace_back<dballe::db::CursorSummary&, bool&> (this=0xa85970)
    at /usr/include/c++/4.8.3/bits/vector.tcc:101
#7  dballe::db::Summary::add_summary (this=0xa858a0, cur=..., with_details=true) at db/summary.cc:107
#8  0x0000000000452272 in provami::Model::on_have_new_summary() ()
#9  0x000000000045a895 in provami::Model::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#10 0x00000035754bdca1 in QMetaObject::activate(QObject*, int, int, void**) () from /lib64/libQt5Core.so.5
#11 0x000000357529b4da in QFutureWatcherBase::event(QEvent*) () from /lib64/libQt5Core.so.5
#12 0x0000003572d5be8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#13 0x0000003572d61096 in QApplication::notify(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#14 0x000000357548ce25 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#15 0x000000357548ee17 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib64/libQt5Core.so.5
#16 0x00000035754e7a03 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /lib64/libQt5Core.so.5
#17 0x000000385f6492a6 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#18 0x000000385f649628 in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#19 0x000000385f6496dc in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#20 0x00000035754e6e2c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /lib64/libQt5Core.so.5
#21 0x000000357548ac8b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#22 0x0000003575492686 in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
#23 0x000000000042b377 in main ()
(gdb) 
```

**Comment by spanezz** [comment]
Sistemato. Richiede dballe dal commit ARPA-SIMC/dballe@b8ae81f46aedd5a47cc4a19573436617c40d3402 in poi.

**Comment by brancomat** [comment]
packaged in dballe v7.12
